import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { normalizeError, createErrorResponse } from "@/lib/api/errors";
import { rateLimit } from "@/lib/rate-limit";
import { z } from "zod";

const RATE_LIMIT = {
  key: (ip: string) => `rate-limit:cfo-pack:${ip}`,
  limit: 5,
  windowMs: 60 * 60 * 1000, // 5 per hour
};

const CfoPackSchema = z.object({
  email: z.string().email(),
  name: z.string().optional(),
  buildCode: z.string().optional(),
  role: z.string().optional(),
});

export async function POST(req: NextRequest) {
  try {
    const origin = req.headers.get("origin");
    const host = req.headers.get("host");
    if (origin) {
       const originUrl = new URL(origin);
       if (!host || originUrl.host !== host) {
          if (process.env.NODE_ENV !== "development") {
            return createErrorResponse("FORBIDDEN", "Invalid origin");
          }
       }
    }

    const ip = req.headers.get("x-forwarded-for") || "anonymous";
    const { success } = await rateLimit({
      key: RATE_LIMIT.key(ip),
      limit: RATE_LIMIT.limit,
      windowMs: RATE_LIMIT.windowMs,
    });

    if (!success) return createErrorResponse("RATE_LIMIT_EXCEEDED", "Too many requests");

    const body = await req.json();
    const { email, name, buildCode, role } = CfoPackSchema.parse(body);

    // Create Lead
    await prisma.lead.create({
      data: {
        email,
        name: name || "Unknown",
        source: "cfo_pack",
        status: "new",
        message: buildCode ? `Downloaded CFO Pack for build ${buildCode}` : "Downloaded CFO Pack",
        role,
      }
    });

    // Fetch build data if available
    let buildData = null;
    if (buildCode) {
      const build = await prisma.infraBuild.findUnique({ where: { code: buildCode } });
      if (build) {
        buildData = {
          specs: JSON.parse(build.skuSnapshotJson),
          metrics: JSON.parse(build.computedTotalsJson),
        };
      }
    }

    // Generate HTML Report (Server-Side)
    const reportHtml = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>CFO Defense Pack - Vantus Systems</title>
        <style>
          body { font-family: sans-serif; padding: 40px; color: #333; max-width: 800px; margin: 0 auto; }
          h1 { border-bottom: 2px solid #000; padding-bottom: 10px; }
          .highlight { background: #eee; padding: 20px; border-radius: 8px; margin: 20px 0; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
          th { background: #f9f9f9; }
          .footer { margin-top: 50px; font-size: 0.8em; color: #666; }
        </style>
      </head>
      <body>
        <h1>CFO Defense Pack</h1>
        <p>Prepared for: ${email}</p>
        <p>Date: ${new Date().toLocaleDateString()}</p>

        <div class="highlight">
          <h2>Executive Summary</h2>
          <p>This document outlines the TCO analysis and hardware specification required to support the target workload, avoiding cloud rental premiums.</p>
        </div>

        ${buildData ? `
        <h2>Proposed Infrastructure</h2>
        <table>
          <tr><th>Component</th><th>Specification</th></tr>
          <tr><td>CPU</td><td>${buildData.specs.cpuModel || "Custom"}</td></tr>
          <tr><td>RAM</td><td>${buildData.specs.ramGB} GB</td></tr>
          <tr><td>Storage</td><td>${buildData.specs.storageDrives?.[0]?.qty}x ${buildData.specs.storageDrives?.[0]?.sizeGB}GB</td></tr>
        </table>

        <h2>Financial Impact</h2>
        <table>
          <tr><th>Metric</th><th>Value</th></tr>
          <tr><td>Monthly Hardware TCO</td><td>$${buildData.metrics.totalCostMonthly}</td></tr>
          <tr><td>Power Consumption</td><td>${buildData.metrics.powerDrawWatts} W</td></tr>
        </table>
        ` : `<p>No specific build context provided. This is a general template.</p>`}

        <h2>Risk Register</h2>
        <ul>
           <li><strong>Vendor Lock-in:</strong> Mitigated by using standard x86/ARM commodity hardware.</li>
           <li><strong>Data Sovereignty:</strong> Data resides on owned/leased hardware, not shared multi-tenant storage.</li>
           <li><strong>Cost Unpredictability:</strong> Fixed monthly costs vs. variable cloud usage fees.</li>
        </ul>

        <div class="footer">
          Generated by Vantus Systems Truth Engine.
        </div>
      </body>
      </html>
    `;

    return new NextResponse(reportHtml, {
      headers: {
        "Content-Type": "text/html",
        "Content-Disposition": `attachment; filename="Vantus-CFO-Defense-Pack-${buildCode || "Template"}.html"`,
        "Cache-Control": "no-store",
      }
    });

  } catch (error) {
    return normalizeError(error);
  }
}
