export const COMMON_PASSWORD_LIST = [
  "password", "123456", "12345678", "1234", "qwerty", "12345", "dragon",
  "baseball", "football", "letmein", "monkey", "abc123", "mustang",
  "michael", "shadow", "master", "jennifer", "111111", "2000",
  "jordan", "superman", "harley", "1234567", "freedom", "whatever",
  "trustno1", "sunshine", "iloveyou", "starwars", "bailey", "jesus",
  "nicholas", "matthew", "hello", "azerty", "654321", "password1",
  "admin", "welcome", "login", "passw0rd", "master", "hello123",
  "freedom", "whatever", "trustno1", "696969", "batman", "spiderman",
  "superman", "ironman", "hulk", "thor", "captain", "america", "avenger",
  "wolverine", "deadpool", "gandalf", "frodo", "bilbo", "legolas", "aragorn",
  "gimli", "sauron", "darth", "vader", "luke", "leia", "han", "solo", "yoda",
  "obiwan", "anakin", "padme", "chewbacca", "r2d2", "c3po", "boba", "fett",
  "jabba", "palpatine", "skywalker", "kenobi", "sith", "jedi", "tatooine",
  "hoth", "endor", "dagobah", "naboo", "coruscant", "kashyyyk", "mustafar",
  "alderaan", "bespin", "geonosis", "kamino", "utapau", "felucia", "mygeeto",
  "saleucami", "cato", "neimoidia", "kessel", "ord", "mantell", "byss",
  "dantooine", "yavin", "hoth", "dagobah", "endor", "jakku", "takodana",
  "starkiller", "ahchto", "crait", "exegol", "pasaana", "kijimi", "ajan",
  "kloss", "chandrila", "corellia", "dathomir", "felucia", "geonosis",
  "hoth", "kamino", "kashyyyk", "mustafar", "mygeeto", "naboo", "ord",
  "mantell", "saleucami", "scarif", "sullust", "tatooine", "utapau",
  "yavin", "zakarr", "zakuul", "ziost", "abregado", "alderaan", "anch",
  "toine", "bastion", "bespin", "byss", "cato", "neimoidia", "chandrila",
  "corellia", "dantooine", "dathomir", "dagobah", "endor", "felucia",
  "geonosis", "hoth", "jakku", "kamino", "kashyyyk", "korriban",
  "malachor", "mandalore", "mantell", "mon", "calamari", "mustafar",
  "mygeeto", "naboo", "ord", "mantell", "pasaana", "quermia", "raleigh",
  "rishi", "ruusan", "saleucami", "scarif", "serenno", "sullust",
  "tatooine", "takodana", "utapau", "yavin", "zakarr", "zakuul", "ziost"
];
